FROM python:3.6-slim

RUN mkdir -p /usr/src/app && pip install --upgrade pip
WORKDIR /usr/src/app

#COPY requirements.txt data/ src/ /usr/src/app/
COPY requirements.txt src/ /usr/src/app/

# Server dockerfile gets access to the data
RUN pip install --no-cache-dir -r requirements.txt

# create the grpc files
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. sgd_svm.proto

# When launching a container, run the server
CMD ["python", "sgd_svm_server.py"]
