# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sgd_svm_pb2 as sgd__svm__pb2


class SGDSVMStub(object):
  """Interface exported by the server.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getDataLabels = channel.unary_unary(
        '/sgdsvm.SGDSVM/getDataLabels',
        request_serializer=sgd__svm__pb2.Auth.SerializeToString,
        response_deserializer=sgd__svm__pb2.Data.FromString,
        )
    self.auth = channel.unary_unary(
        '/sgdsvm.SGDSVM/auth',
        request_serializer=sgd__svm__pb2.Empty.SerializeToString,
        response_deserializer=sgd__svm__pb2.Auth.FromString,
        )
    self.sendGradientUpdate = channel.unary_unary(
        '/sgdsvm.SGDSVM/sendGradientUpdate',
        request_serializer=sgd__svm__pb2.GradientUpdate.SerializeToString,
        response_deserializer=sgd__svm__pb2.Empty.FromString,
        )
    self.sendDoneComputing = channel.unary_unary(
        '/sgdsvm.SGDSVM/sendDoneComputing',
        request_serializer=sgd__svm__pb2.Empty.SerializeToString,
        response_deserializer=sgd__svm__pb2.Empty.FromString,
        )


class SGDSVMServicer(object):
  """Interface exported by the server.
  """

  def getDataLabels(self, request, context):
    """A simple RPC.
    Obtains the feature at a given position.
    A feature with an empty name is returned if there's no feature at the given
    position.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def auth(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendGradientUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendDoneComputing(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SGDSVMServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getDataLabels': grpc.unary_unary_rpc_method_handler(
          servicer.getDataLabels,
          request_deserializer=sgd__svm__pb2.Auth.FromString,
          response_serializer=sgd__svm__pb2.Data.SerializeToString,
      ),
      'auth': grpc.unary_unary_rpc_method_handler(
          servicer.auth,
          request_deserializer=sgd__svm__pb2.Empty.FromString,
          response_serializer=sgd__svm__pb2.Auth.SerializeToString,
      ),
      'sendGradientUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.sendGradientUpdate,
          request_deserializer=sgd__svm__pb2.GradientUpdate.FromString,
          response_serializer=sgd__svm__pb2.Empty.SerializeToString,
      ),
      'sendDoneComputing': grpc.unary_unary_rpc_method_handler(
          servicer.sendDoneComputing,
          request_deserializer=sgd__svm__pb2.Empty.FromString,
          response_serializer=sgd__svm__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'sgdsvm.SGDSVM', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
