# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgd_svm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgd_svm.proto',
  package='sgdsvm',
  syntax='proto3',
  serialized_pb=_b('\n\rsgd_svm.proto\x12\x06sgdsvm\":\n\x0eGradientUpdate\x12\x1c\n\x14gradient_update_json\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\"G\n\x04\x44\x61ta\x12\x14\n\x0csamples_json\x18\x01 \x01(\t\x12\x13\n\x0blabels_json\x18\x02 \x01(\t\x12\x14\n\x0cweights_json\x18\x03 \x01(\t\"\x12\n\x04\x41uth\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\xd2\x01\n\x06SGDSVM\x12-\n\rgetDataLabels\x12\x0c.sgdsvm.Auth\x1a\x0c.sgdsvm.Data\"\x00\x12%\n\x04\x61uth\x12\r.sgdsvm.Empty\x1a\x0c.sgdsvm.Auth\"\x00\x12=\n\x12sendGradientUpdate\x12\x16.sgdsvm.GradientUpdate\x1a\r.sgdsvm.Empty\"\x00\x12\x33\n\x11sendDoneComputing\x12\r.sgdsvm.Empty\x1a\r.sgdsvm.Empty\"\x00\x62\x06proto3')
)




_GRADIENTUPDATE = _descriptor.Descriptor(
  name='GradientUpdate',
  full_name='sgdsvm.GradientUpdate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gradient_update_json', full_name='sgdsvm.GradientUpdate.gradient_update_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='sgdsvm.GradientUpdate.id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=83,
)


_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='sgdsvm.Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='samples_json', full_name='sgdsvm.Data.samples_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='labels_json', full_name='sgdsvm.Data.labels_json', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weights_json', full_name='sgdsvm.Data.weights_json', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=156,
)


_AUTH = _descriptor.Descriptor(
  name='Auth',
  full_name='sgdsvm.Auth',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='sgdsvm.Auth.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=176,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='sgdsvm.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=185,
)

DESCRIPTOR.message_types_by_name['GradientUpdate'] = _GRADIENTUPDATE
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['Auth'] = _AUTH
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GradientUpdate = _reflection.GeneratedProtocolMessageType('GradientUpdate', (_message.Message,), dict(
  DESCRIPTOR = _GRADIENTUPDATE,
  __module__ = 'sgd_svm_pb2'
  # @@protoc_insertion_point(class_scope:sgdsvm.GradientUpdate)
  ))
_sym_db.RegisterMessage(GradientUpdate)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), dict(
  DESCRIPTOR = _DATA,
  __module__ = 'sgd_svm_pb2'
  # @@protoc_insertion_point(class_scope:sgdsvm.Data)
  ))
_sym_db.RegisterMessage(Data)

Auth = _reflection.GeneratedProtocolMessageType('Auth', (_message.Message,), dict(
  DESCRIPTOR = _AUTH,
  __module__ = 'sgd_svm_pb2'
  # @@protoc_insertion_point(class_scope:sgdsvm.Auth)
  ))
_sym_db.RegisterMessage(Auth)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'sgd_svm_pb2'
  # @@protoc_insertion_point(class_scope:sgdsvm.Empty)
  ))
_sym_db.RegisterMessage(Empty)



_SGDSVM = _descriptor.ServiceDescriptor(
  name='SGDSVM',
  full_name='sgdsvm.SGDSVM',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=188,
  serialized_end=398,
  methods=[
  _descriptor.MethodDescriptor(
    name='getDataLabels',
    full_name='sgdsvm.SGDSVM.getDataLabels',
    index=0,
    containing_service=None,
    input_type=_AUTH,
    output_type=_DATA,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='auth',
    full_name='sgdsvm.SGDSVM.auth',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_AUTH,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendGradientUpdate',
    full_name='sgdsvm.SGDSVM.sendGradientUpdate',
    index=2,
    containing_service=None,
    input_type=_GRADIENTUPDATE,
    output_type=_EMPTY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendDoneComputing',
    full_name='sgdsvm.SGDSVM.sendDoneComputing',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SGDSVM)

DESCRIPTOR.services_by_name['SGDSVM'] = _SGDSVM

# @@protoc_insertion_point(module_scope)
